# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the action', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the action', max_length=50)),
                ('description', models.CharField(help_text='Description of the action', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event (i.e. 'Play', 'Vibrate')", max_length=50)),
            ],
        ),
    ]
