# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text=b'Name of the event Ex- Play, Vibrate', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text=b'Unique id for the sequence', primary_key=True, serialize=False)),
                ('events_sequence', models.ManyToManyField(help_text=b'Add Event', to='appstager.Event')),
            ],
        ),
    ]
