# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 04:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the action', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of the action', max_length=200)),
                ('action_type', models.CharField(choices=[('Vibrate', 'Vibrate'), ('Background', 'Background'), ('Sound', 'Sound'), ('Image', 'Image'), ('Video', 'Video')], help_text='Name of the action type', max_length=50)),
                ('order', models.IntegerField(help_text='Order of the action in the show (from QLab)', null=True)),
                ('duration', models.DurationField(default=datetime.timedelta, help_text='Duration of the action (HH:MM:SS)')),
                ('redValue', models.CharField(default='0', help_text='The value of the color red that should be used', max_length=3)),
                ('greenValue', models.CharField(default='0', help_text='The value of the color green that should be used', max_length=3)),
                ('blueValue', models.CharField(default='0', help_text='The value of the color blue that should be used', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Show', max_length=100, unique=True)),
                ('number_of_seats', models.IntegerField(help_text='Input the number of seats this theater has', null=True)),
                ('director', models.CharField(default='Director of this show', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Theater', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appstager.Theater'),
        ),
        migrations.AddField(
            model_name='action',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstager.Show'),
        ),
    ]
