# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appstager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text=b'Unique id for the sequence', primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text=b"Name of the event Ex- 'Play', 'Vibrate'", max_length=30),
        ),
        migrations.AddField(
            model_name='sequence',
            name='events_sequence',
            field=models.ManyToManyField(help_text=b'Add Event', to='appstager.Event'),
        ),
    ]
