# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appstager', '0002_auto_20171025_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the action', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the action', max_length=50)),
                ('description', models.CharField(help_text='Description of the action', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event (i.e. 'Play', 'Vibrate')", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='events_sequence',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
    ]
